"""Initial database schema

Revision ID: 0001
Revises: 
Create Date: 2025-07-09 03:08:13.123456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('soul_type', sa.String(), nullable=False),
    sa.Column('evangelism_type', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('completed_membership', sa.Boolean(), nullable=True),
    sa.Column('completed_new_believers', sa.Boolean(), nullable=True),
    sa.Column('is_baptised', sa.Boolean(), nullable=True),
    sa.Column('completed_spiritual_maturity', sa.Boolean(), nullable=True),
    sa.Column('first_attendance_date', sa.DateTime(), nullable=True),
    sa.Column('last_attendance_date', sa.DateTime(), nullable=True),
    sa.Column('soul_winner', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('point_of_contact', sa.String(), nullable=False),
    sa.Column('branch_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_events',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('branch_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('event_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['service_events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    op.drop_table('service_events')
    op.drop_table('members')
    op.drop_table('branches')
    # ### end Alembic commands ###